#!/usr/bin/env python3
"""Configure and build ask_user_gate, dropping the binary next to hooks.json.

It regenerates the port's option table first (OPTIONS_INC below).

One call rather than a configure-then-build chain: the gate this builds refuses
chained shell commands, and a build recipe that has to be typed as one would be
a poor advertisement for it.

  python cpp/build.py                 # Release, incremental
  python cpp/build.py --clean         # throw away the CMake cache first
  python cpp/build.py --config Debug
"""

import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR = os.path.join(HERE, "build")
HOOKS_DIR = os.path.normpath(os.path.join(HERE, os.pardir, "hooks"))
REFERENCE = os.path.join(HOOKS_DIR, "ask_user_gate.py")

# The port's option table, generated from the reference's build_parser() and
# #included by ask_user_gate.cpp as the body of kOptions -- so an option added
# to the script reaches the port through a build, not through a hand copy that
# a test had to parse back out of C++.
#
# COMMITTED, not written into build/ only, and regenerated by every run of
# this script. Committed because the check that needs no compiler is the one
# that runs everywhere: tests/test_ask_user_gate_parity.py compares the file
# with options_inc() on every checkout and CI interpreter, none of which build
# the port (it is a local, Windows, opt-in build; the marketplace ships the
# script). A build-time-only file would move that check to the machines that
# compile, and a plain `cmake --build` would then need Python to find. What a
# plain CMake build without this script can do is compile a STALE table;
# the freshness test fails on it, and parity_check's per-option rows DIFF.
# parity_check counts the file among the sources a binary must be newer than.
OPTIONS_INC = os.path.join(HERE, "kOptions.inc")

# What a generated name may be: it goes into a C++ string literal unescaped.
OPTION_NAME = re.compile(r"-{1,2}[A-Za-z0-9][A-Za-z0-9-]*\Z")


def reference_parser() -> argparse.ArgumentParser:
    """build_parser() of the reference, loaded by path: this script is run
    from anywhere, and the reference is not a package."""
    spec = importlib.util.spec_from_file_location("ask_user_gate_reference",
                                                  REFERENCE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.build_parser()


def options_inc(parser: "argparse.ArgumentParser | None" = None) -> str:
    """The text of OPTIONS_INC: one kOptions entry per option string.

    The port knows two arities, a flag and exactly one value, so any other
    nargs is refused here rather than written as one of them: `nargs="?"`
    spelled Arity::Value would make the port demand a value the script lets
    go missing.
    """
    if parser is None:
        parser = reference_parser()
    lines = ["// Generated by cpp/build.py from build_parser() in "
             "hooks/ask_user_gate.py;",
             "// do not edit. tests/test_ask_user_gate_parity.py fails while it "
             "is stale."]
    for action in parser._actions:
        if action.nargs not in (0, None):
            raise ValueError(f"{'/'.join(action.option_strings) or action.dest} "
                             f"has nargs={action.nargs!r}; the port's kOptions "
                             f"knows only flags and one-value options")
        for option in action.option_strings:
            if not OPTION_NAME.match(option):
                raise ValueError(f"{option!r} cannot be written into kOptions "
                                 f"as it stands")
            arity = "None" if action.nargs == 0 else "Value"
            lines.append(f'{{"{option}", Arity::{arity}}},')
    return "\n".join(lines) + "\n"


def write_options_inc() -> bool:
    """Regenerate OPTIONS_INC; True when it changed. Written only on a change,
    so its mtime -- which parity_check reads -- moves only with its content.
    Read in text mode: a checkout under core.autocrlf holds it with CRLF, which
    is the same table and must not count as a change."""
    text = options_inc()
    try:
        with open(OPTIONS_INC, encoding="utf-8") as handle:
            if handle.read() == text:
                return False
    except FileNotFoundError:
        pass
    with open(OPTIONS_INC, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)
    return True


def run(command: "list[str]") -> None:
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", default="Release",
                        choices=("Release", "Debug", "RelWithDebInfo",
                                 "MinSizeRel"))
    parser.add_argument("--clean", action="store_true",
                        help="delete the build directory before configuring")
    parser.add_argument("--generator", default=None,
                        help="CMake generator (default: CMake's own choice)")
    parser.add_argument("--no-self-test", action="store_true",
                        help="skip the --self-test run after a successful build")
    options = parser.parse_args()

    if shutil.which("cmake") is None:
        print("cmake is not on PATH. On this machine it ships with Visual "
              "Studio 2022 -- run this from a Developer prompt, or add "
              "'<VS>/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin' "
              "to PATH.", file=sys.stderr)
        return 2

    if options.clean and os.path.isdir(BUILD_DIR):
        shutil.rmtree(BUILD_DIR)

    if write_options_inc():
        print(f"regenerated {OPTIONS_INC} from the reference's build_parser() "
              f"-- commit it with the change that moved the options")

    configure = ["cmake", "-S", HERE, "-B", BUILD_DIR,
                 f"-DCMAKE_BUILD_TYPE={options.config}"]
    if options.generator:
        configure += ["-G", options.generator]
    run(configure)
    # --config is ignored by single-config generators and required by the
    # multi-config one Visual Studio brings, so it is always passed.
    run(["cmake", "--build", BUILD_DIR, "--config", options.config])

    exe = os.path.join(HOOKS_DIR,
                       "ask_user_gate.exe" if os.name == "nt" else "ask_user_gate")
    if not os.path.isfile(exe):
        print(f"build reported success but {exe} is not there", file=sys.stderr)
        return 1
    # Size is the thing the Release flags buy (see CMakeLists.txt), so it is
    # printed on every build rather than measured only when someone suspects it.
    print(f"built {exe} ({os.path.getsize(exe) / 1024:.0f} KiB)")
    if options.no_self_test:
        return 0
    return subprocess.run([exe, "--self-test"]).returncode


if __name__ == "__main__":
    sys.exit(main())
